[2025-01-27T12:29:30.396+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T12:29:30.424+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sales_order_ingestion.ingest_sales_order_data manual__2025-01-27T12:29:29.175365+00:00 [queued]>
[2025-01-27T12:29:30.433+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sales_order_ingestion.ingest_sales_order_data manual__2025-01-27T12:29:29.175365+00:00 [queued]>
[2025-01-27T12:29:30.433+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-27T12:29:30.440+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): ingest_sales_order_data> on 2025-01-27 12:29:29.175365+00:00
[2025-01-27T12:29:30.445+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-27T12:29:30.446+0000] {standard_task_runner.py:72} INFO - Started process 207 to run task
[2025-01-27T12:29:30.446+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sales_order_ingestion', 'ingest_sales_order_data', 'manual__2025-01-27T12:29:29.175365+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpca12ybs3']
[2025-01-27T12:29:30.447+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask ingest_sales_order_data
[2025-01-27T12:29:30.633+0000] {task_command.py:467} INFO - Running <TaskInstance: sales_order_ingestion.ingest_sales_order_data manual__2025-01-27T12:29:29.175365+00:00 [running]> on host 7f1a1600171e
[2025-01-27T12:29:30.725+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sales_order_ingestion' AIRFLOW_CTX_TASK_ID='ingest_sales_order_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T12:29:29.175365+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-27T12:29:29.175365+00:00'
[2025-01-27T12:29:30.726+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-27T12:29:30.726+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-27T12:29:30.726+0000] {logging_mixin.py:190} INFO - Current task name:ingest_sales_order_data state:running start_date:2025-01-27 12:29:30.424993+00:00
[2025-01-27T12:29:30.727+0000] {logging_mixin.py:190} INFO - Dag name:sales_order_ingestion and current dag run status:running
[2025-01-27T12:29:30.727+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T12:29:31.604+0000] {logging_mixin.py:190} INFO - response is  <Response [200]>
[2025-01-27T12:29:32.705+0000] {logging_mixin.py:190} INFO - response is  <Response [200]>
[2025-01-27T12:33:13.100+0000] {local_task_job_runner.py:346} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2025-01-27T12:33:13.101+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-27T12:33:13.102+0000] {process_utils.py:132} INFO - Sending 15 to group 207. PIDs of all processes in the group: [207]
[2025-01-27T12:33:13.102+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 207
[2025-01-27T12:33:13.103+0000] {taskinstance.py:3093} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-01-27T12:33:13.122+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T12:33:13.155+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=207, status='terminated', exitcode=0, started='12:29:29') (207) terminated with exit code 0
